"""add suggestions and reviews

Revision ID: 6735865e5ba0
Revises: b5a238e87971
Create Date: 2026-09-02 09:23:01.723976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6735865e5ba0'
down_revision: Union[str, Sequence[str], None] = 'b5a238e87971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('guard_accepted', sa.Boolean(), nullable=False),
    sa.Column('guard_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'image_id', name='uq_suggestion_post_image')
    )
    op.create_index('ix_suggestions_post_id', 'suggestions', ['post_id'], unique=False)
    op.create_index('ix_suggestions_status', 'suggestions', ['status'], unique=False)
    op.create_table('suggestion_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_reviews_suggestion_id'), 'suggestion_reviews', ['suggestion_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_reviews_suggestion_id'), table_name='suggestion_reviews')
    op.drop_table('suggestion_reviews')
    op.drop_index('ix_suggestions_status', table_name='suggestions')
    op.drop_index('ix_suggestions_post_id', table_name='suggestions')
    op.drop_table('suggestions')
    # ### end Alembic commands ###
