"""add processing jobs and ai cost logs

Revision ID: 68141a89e86b
Revises: 3fec335204a9
Create Date: 2026-09-01 12:07:42.449425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68141a89e86b'
down_revision: Union[str, Sequence[str], None] = '3fec335204a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cost_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('operation', sa.String(
                        length=100), nullable=False),
                    sa.Column('model_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('resource_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('resource_id', sa.Integer(), nullable=True),
                    sa.Column('input_tokens', sa.Integer(), nullable=False),
                    sa.Column('output_tokens', sa.Integer(), nullable=False),
                    sa.Column('estimated_cost_usd', sa.Numeric(
                        precision=12, scale=8), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ai_cost_logs_operation'),
                    'ai_cost_logs', ['operation'], unique=False)
    op.create_table('processing_jobs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('job_type', sa.String(
                        length=100), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('total_items', sa.Integer(), nullable=False),
                    sa.Column('processed_items', sa.Integer(), nullable=False),
                    sa.Column('failed_items', sa.Integer(), nullable=False),
                    sa.Column('error_message', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('started_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('completed_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_processing_jobs_job_type'),
                    'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'),
                    'processing_jobs', ['status'], unique=False)
    op.add_column(
        "images",
        sa.Column(
            "processing_attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column('images', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'last_error')
    op.drop_column('images', 'processing_attempts')
    op.drop_index(op.f('ix_processing_jobs_status'),
                  table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'),
                  table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_ai_cost_logs_operation'), table_name='ai_cost_logs')
    op.drop_table('ai_cost_logs')
    # ### end Alembic commands ###
